import React from 'react'

               /*
               This code This code defines a React functional component called Tickets Card It 
               returns a JSX element that renders an image and a button with a link The image source 
               is set to static images tickets Tickt 3 png and the button has text Buy Now The 
               CSS classes are used for styling purposes such as setting background color padding 
               font size etc
               - generated by stenography autopilot [ 🚗👩‍✈️ ]
               */
export default function TicketsCard() {
  return (
    <div className='bg-cardBackground p-4 pb-8 rounded flex flex-col items-center space-y-4'>
        <img src="/static/images/tickets/Tickt3.png" alt=""  />
        <a href="#tickets" className="mt-8 px-8 py-2 bg-button text-white text-lg font-semibold rounded-sm shadow-md hover:bg-transparent hover:border hover:border-white ">Buy Now</a>
    </div>
  )
}
