import React from 'react'

               /*
               This code This code defines a React functional component called Tickets Card It 
               returns a JSX element that renders an image and a button with a link The image source 
               is set to static images tickets Tickt 3 png and the button has text Buy Now The 
               CSS classes are used for styling purposes such as setting background color padding 
               font size etc
               - generated by stenography autopilot [ 🚗👩‍✈️ ]
               */
export default function TicketsCard(props: TicketProps) {
  const {src, phone, message} = props

  // Construct the WhatsApp URL
  const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

  return (
    <div className=' shadow-lg   pb-8 rounded-md flex flex-col items-center space-y-4'>
        <img src= {src} alt=""  />
        <a href={url} className="mt-8 px-8 py-2 bg-button text-white text-lg font-semibold rounded-lg shadow-md hover:text-primary hover:bg-transparent  hover:border hover:border-white ">Buy Now</a>
    </div>
  )
}

type TicketProps = {
  src: string,
  phone: string,
  message: string,
}

